# Site settings
title: WDW
email: info@scottylabs.org
description: "A talk series comprised of interactive workshops that teach the fundamentals of web development."
baseurl: "/wdw"
url: "http://scottylabs.org"

exclude:
  - README.md
  - LICENSE
  - Gemfile.lock
  - Gemfile

# Build settings
markdown: redcarpet
highlight: pygments

sass:
  sass_dir: _sass
  style: compressed

redcarpet:
  extensions:
    - smart
    - tables
    - with_toc_data

permalink: pretty

# custom configuration
registration_link: https://docs.google.com/forms/d/18kKgkeUjIpzmXJyElnX1Htzyx7ivQeejImcq8-RTYHg/viewform

# The order that pages should be displayed int the menu bar
wdw_pages:
  - basics
  - design
  - frontend
  - html
  - backend
  - deployment
