# Site settings
title: WDW
description: "A talk series comprised of interactive workshops that teach the fundamentals of web development."
baseurl: "/wdw"
url: "https://scottylabs.org"

exclude:
  - README.md
  - LICENSE
  - Gemfile.lock
  - Gemfile

# Build settings
sass:
  sass_dir: _sass
  style: compressed

permalink: pretty

# custom configuration
registration_link: https://forms.gle/H6PXxyXhVAxsSTPVA
attendance_link: https://forms.gle/5jYSgHkMZi8uKeDo9

# The order that pages should be displayed int the menu bar
wdw_pages:
  - basics
  - html+css
  - javascript
  - rest
  - react
  - chrome extension
  - backend

