# Site settings
title: Web Dev Weeks
email: info@scottylabs.org
description: "An talk series comprised of interactive workshops that teach the fundamentals of web development."
baseurl: "/wdw"
url: "http://scottylabs.org"

exclude:
  - README.md
  - LICENSE
  - Gemfile.lock
  - Gemfile

# Build settings
markdown: redcarpet
highlight: pygments

sass:
  sass_dir: _sass
  style: compressed

redcarpet:
  extensions:
    - smart
    - tables
    - with_toc_data

permalink: pretty
