# Site settings
title: WDW
description: "A talk series comprised of interactive workshops that teach the fundamentals of web development."
baseurl: ""
url: "https://wdw.scottylabs.org"

exclude:
  - README.md
  - LICENSE
  - Gemfile.lock
  - Gemfile

# Build settings
sass:
  sass_dir: _sass
  style: compressed

permalink: pretty

# custom configuration
registration_link: https://forms.gle/zLJQqwgEzvXtVDzDA
attendance_link: https://forms.gle/5jYSgHkMZi8uKeDo9
zoom_link: https://href.scottylabs.org/wdw-zoom

wdw_start_time: "October 10, 2020 12:00:00"

# The order that pages should be displayed int the menu bar
wdw_pages:
  - basics
  - git
  - html+css
  - javascript
  - flask
  - express
  - react
  - deployment

