# Site settings
title: Web Dev Weeks
email: info@scottylabs.org
description: ""
baseurl: "/webdevweeks"
url: ""

# Build settings
markdown: redcarpet
highlight: pygments

redcarpet:
  extensions: [smart, tables, with_toc_data]

permalink: pretty
