# Site settings
title: WDW
description: "A talk series comprised of interactive workshops that teach the fundamentals of web development."
baseurl: "/wdw"
url: "https://scottylabs.org"

exclude:
  - README.md
  - LICENSE
  - Gemfile.lock
  - Gemfile

# Build settings
sass:
  sass_dir: _sass
  style: compressed

permalink: pretty

# custom configuration
registration_link: https://docs.google.com/forms/d/e/1FAIpQLSeR5Zwwo2hIszTzXC_oohsBylDHh0V2qf7CjVq5jRppu4ZGow/viewform?usp=sf_link

# The order that pages should be displayed int the menu bar
wdw_pages:
  - basics
  - html
  - javascript
  - design
  - react
  - p5

